#!/usr/bin/perl -w

use strict;
use warnings;
use Switch;
use File::Basename;
use Cwd 'abs_path';

my $usage = <<_EOUSAGE_;

Usage: ascp-utils <command> <arguments>
version: 0.0.1
supports:

    sra <list>
    ftp <list>
    ena <list>

Licenced:
(c) 2018-2020 - LEI ZHANG
Logic Informatics Co.,Ltd.
zhanglei\@logicinformatics.com

_EOUSAGE_
;

if( ( scalar @ARGV) < 1){
    printf STDERR $usage;
    exit;

}

my $which = "";
for my $exe (qw/prefetch ascp/) {
    $which  = qx(which $exe 2> /dev/null);
    $which or print STDERR qq{[ERR]: can not find required '$exe' in PATH\n};
  	chomp $which;
}
my $ascp =  dirname( $which ) . '/..';

my $cmd  = shift @ARGV;

switch($cmd){

    case 'sra'   { sra_run(); };
    case 'ftp'   { ftp_run(); };
    case 'ena'   { ena_run(); };

}

exit;

sub sra_run{

    if(@ARGV < 1){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    my $cmd = qq{prefetch   \
    	          -t fasp   \
    	          -a "$ascp/bin/ascp|$ascp/etc/asperaweb_id_dsa.openssh" \
    	          --ascp-options " --overwrite=diff -QTr -l6000m "       \
    	          -L debug -O . } . join(" ", @ARGV) . "\n";
    
       $cmd =~ s/\s+\n\s+/ /msg;
    print $cmd;
    system $cmd;

}

sub ftp_run{

    if(@ARGV < 1){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    foreach my $acc (@ARGV) {
         ftp( $acc );
    }

}

sub ftp {
    
   my $url = shift;
      $url  =~ s/ftp:\/\/.+.ncbi.nlm.nih.gov//;
      $url  =~ s/https:\/\/.+.ncbi.nlm.nih.gov//;
      $url  =~ s/https:\/\/ftp.ncbi.nih.gov//;

   my $ftp  = qq{$ascp/bin/ascp -i $ascp/etc/asperaweb_id_dsa.openssh --overwrite=diff -QTr -l6000m anonftp\@ftp.ncbi.nlm.nih.gov:};
   my $ascp = $ftp . $url . " .\n";

   print  $ascp;
   system $ascp;

}


sub ena_run{

    if(@ARGV < 1){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    my $list = shift @ARGV;
    ascp_ena( $list );

}

sub ascp_ena {
  
  my $list = shift;
  open( ENA,  $list )   || die "[ERR]: can't open $list. \n";
  while(<ENA>){
        $_ =~ s/\s+$//;
        next if(/study_accession/);
        my @t = split /\t/, $_;
        ena($t[-1]);
  }
  close ENA;

}

sub ena{

   my $url = shift;
      $url  =~ s/ftp.sra.ebi.ac.uk\///;

   my $ftp  = qq{$ascp/bin/ascp -i $ascp/etc/asperaweb_id_dsa.openssh  -QT -P33001 -QT -l6000m era-fasp\@fasp.sra.ebi.ac.uk:};
   my $ascp = $ftp . $url . " .\n";

   print  $ascp;

}
